### ISSUE TITLE
installing stravalib

### ISSUE THREAD

**Issue by pyrat** [dlenski/stravacli#3]
Hi there,

Looks like an excellent tool. Im running into an issue getting it running with regards to Python and installing the stravalib.

When running I get the following:

➜  stravacli git:(master) ./stravaup.py
Traceback (most recent call last):
  File "./stravaup.py", line 4, in <module>
    from stravalib import Client, exc
ImportError: No module named stravalib

I installed stravalib with 
sudo pip install stravalib

Do I need to do something with PATH to make this available? (on mac btw)

Thanks.

**Comment by dlenski** [comment]
Hmm... hard to say without knowing the details of your Python installation.

I'm going to take a guess that your `pip` defaults to Python **3**, whereas `stravaup.py` uses Python **2**:

```
#!/usr/bin/env python2
```

`pip --version` should tell you whether it's installing packages for Python 2.7 vs Python 3.x.

**Comment by dlenski** [comment]
`stravaup` now uses Python3, and this should be fixed.
