### ISSUE TITLE
API access token site can't be reached

### ISSUE THREAD

**Issue by alex-kowalczyk** [dlenski/stravacli#5]
After granting access on strava screen, you are redirected to error page:

```
This site can’t be reached
stravacli-dlenski.rhcloud.com’s server DNS address could not be found.
```

**Comment by dlenski** [comment]
Yeah, unfortunately RedHat took down their free cloud hosting, and I haven't had time to set up a new one :-(. You can still run your own server to grab the token.

**Comment by dhughes-xumak** [comment]
Strava allows the callback to be localhost, so the Python application could actually create its own short-lived server for receiving the code during the auth flow.

I've taken that approach with my bash-based CLI application:
https://github.com/dlh3/query-strava/blob/060802a7a9c24d602bb976724ee76ae666e2379b/querystrava.sh#L47-L56

**Comment by dlenski** [comment]
> Strava allows the callback to be localhost, so the Python application could actually create its own short-lived server for receiving the code during the author flow.

Yep. `stravacli` can do this. See the `server` branch, which is (mesilly) [described in the README](https://github.com/dlenski/stravacli#server-branch).

**Comment by dlenski** [comment]
At long last, I've integrated the `server` branch into the `master` branch.

So now it will do exactly what @dhughes-xumak suggested, if you specify a `client_id` and `client_secret` in your `~/.stravacli`:

> Strava allows the callback to be localhost, so the Python application could actually create its own short-lived server for receiving the code during the author flow.
